---
# tasks file for navinfo
- name: Namespace for navinfo
  community.kubernetes.k8s:
    state: "{{ navinfo_state }}"
    name: "{{ navinfo_namespace }}"
    api_version: v1
    kind: Namespace

- name: navinfo service
  community.kubernetes.k8s:
    state: "{{ navinfo_state }}"
    namespace: "{{ navinfo_namespace }}"
    template: "{{ item }}"
  with_items:
    # - jiefa.yml.j2
    - journal.yml.j2
    - web.yml.j2
    - web-en.yml.j2
    # - web-uat.yml.j2
    - ingress.yml.j2
  tags:
    - navinfo
